const url = {
  HOME: {
    name: 'Home',
    href: `/`,
    hash: '#home',
    targetBlank: false,
    local: true,
  },
  AGT_TOKEN: {
    name: 'AGT Token',
    href: `/`,
    hash: '#agt-token',
    targetBlank: true,
    local: false,
  },
  TOKENOMICS: {
    name: 'Tokenomics',
    href: `/`,
    hash: '#tokenomics',
    targetBlank: true,
    local: false,
  },
  ASSETS: {
    name: 'Assets',
    href: `/`,
    hash: '#asset',
    targetBlank: true,
    local: false,
  },
  TEAM: {
    name: 'Team',
    href: `/`,
    hash: '#team',
    targetBlank: true,
    local: false,
  },
  ROADMAP: {
    name: 'Roadmap',
    href: `/`,
    hash: '#roadmap',
    targetBlank: true,
    local: false,
  },
  WHITEPAPER: {
    name: 'Whitepaper',
    href: `https://drive.google.com/file/d/1A7Q3T1lk4cq-IkSS6iVNobSrL5lk5ojf/view?usp=sharing`,
    hash: '',
    targetBlank: true,
    local: false,
  },
  SIGN_UP: {
    name: 'Sign up',
    href: `/`,
    hash: '',
    targetBlank: false,
    local: true,
  },
  CTA_PLAY_BETA: {
    name: 'Play Beta',
    href: `/`,
    hash: '',
    targetBlank: true,
    local: false,
  },
  CTA_PRIVATE_SALE_INFO: {
    name: 'Private Sale Info',
    href: `/`,
    hash: '',
    targetBlank: true,
    local: false,
  },
  CTA_READ_ONE_PAGER: {
    name: 'Read One-Pager',
    href: `/`,
    hash: '',
    targetBlank: false,
    local: true,
  },
  SOCIAL_V1: {
    name: 'V1',
    href: `https://twitter.com/armygrid`,
    hash: '',
    targetBlank: true,
    local: false,
  },
  SOCIAL_V2: {
    name: 'V2',
    href: `https://t.me/armygrid`,
    hash: '',
    targetBlank: true,
    local: false,
  },
  SOCIAL_V3: {
    name: 'V3',
    href: `/`,
    hash: '',
    targetBlank: true,
    local: false,
  },
  PRIVACY: {
    name: 'Privacy Policy',
    href: `/`,
    hash: '',
    targetBlank: true,
    local: false,
  },
  TERMS: {
    name: 'Terms Of Use',
    href: `/`,
    hash: '',
    targetBlank: true,
    local: false,
  },
};

export default url;
